### ISSUE TITLE
Require class name

### ISSUE THREAD

**Issue by fgblomqvist** [Kotti/bobtemplates.kotti#4]
When you leave "Name of the package" blank, it prompts you again (it is mandatory). Meanwhile you can leave class name empty, which will result in a syntax error when you later try to run the generated template.

It should be mandatory to fill in a class name too, alternatively a default one should be provided.

**Comment by disko** [comment]
Unmaintained / superceded – please use the scaffold provided by Kotti instead::

  pcreate -s kotti my_project
